### ISSUE TITLE
ASP.NET Core 2.0 Example

### ISSUE THREAD

**Issue by ardalis** [datalust/seq-extensions-logging#19]
Can you update to show how to wire up using revised ASP.NET Core 2.0 application templates?

**Comment by nblumhardt** [comment]
Hi Steve, thanks for getting in touch. I think we need some updates here (minor) to work nicely with 2.0. I should be able to take a look in the next day or two.

Cheers,
Nick

**Comment by nblumhardt** [comment]
Hi Steve,

3.0.0-dev-*, now on NuGet, supports `AddSeq()` on `ILoggingBuilder`:

Code sample: https://github.com/datalust/seq-extensions-logging/blob/dev/example/WebApplication/Startup.cs#L29

Updating the docs now; since the changes are very minor, I expect this will be pushed to release status pretty soon.

Thanks!

**Comment by nevcoBpalacio** [comment]
Nick,

Have plans to develop an application in Core 2.0. What is your most recent update on the Serilog.Exenstions.Logging moving into a production state from dev?

Thank you,

Ben

**Comment by nevcoBpalacio** [comment]
I see Serilog.Exstensions.Logging from 8/27/2017, does this include the items to fix using it with 2.0?

Thanks,
Ben
