### ISSUE TITLE
JsonSafeString isn't working as expected

### ISSUE THREAD

**Issue by radiohe4d** [datalust/seq-extensions-logging#53]
So I've been using Seq successfully now for months and have only now needed to pass a raw JSON string to the logs. 

When passing an object and using the @, the logs in the Seq dashboard have shown the JSON formatted and highlighting like so:

<img src="https://user-images.githubusercontent.com/19432504/234659436-541a30e8-b952-4397-85be-61327751c370.png" width="450" />

I followed this ticket [#51](https://github.com/datalust/seq-extensions-logging/pull/51) to add this Nuget package and pass the raw JSON using the ```new JsonSafeString(json)``` struct.

I used the exact code from the ticket, but it doesnt appear to be formatting the log within the Seq dashboard as I expect.

```c#
var json = "{\"A\": 42}";
_logger.LogInformation("The answer is {Answer}", new JsonSafeString(json));
```

<img src="https://user-images.githubusercontent.com/19432504/234661369-149f2af1-e384-416e-90a2-5d8dadcdae52.png" width="450" />

Any help would be much appreciated as I cannot figure out why it wont format like the example in ticket 51.

### Seq Server Instance:
- Seq 2023.1.9162
- Docker v23.0.4
- Ubuntu 20.04

### Language
C# .NET 6.0

### Nuget Packages:
- Seq.Extensions.Logging v6.1.0
- Serilog.Sinks.Seq v5.2.2

### Program.cs
```c#
builder
    .Host
    .ConfigureLogging(lc => lc.ClearProviders())
    .UseSerilog((ctx, lc) => lc
        .ReadFrom.Configuration(ctx.Configuration)
        .Enrich.WithCorrelationId()
        .Enrich.FromLogContext()
        .Enrich.WithExceptionDetails(
            new DestructuringOptionsBuilder()
                .WithDefaultDestructurers()
                .WithDestructurers(new[] { new DbUpdateExceptionDestructurer() }))
    );
```

### appsettings.json
```json
"Serilog": {
    "MinimumLevel": {
        "Default": "Debug",
        "Override": {
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
        }
    },
    "Using": [
        "Serilog.Sinks.Console",
        "Serilog.Sinks.Seq"
    ],
    "WriteTo": [
        { "Name": "Console" },
        {
            "Name": "Seq",
            "Args": {
                "serverUrl": "<OMITTED>",
                "apiKey": "<OMITTED>"
            }
        }
    ],
    "Properties": {
        "_Application": "<OMITTED>"
    }
},
```

**Comment by nblumhardt** [comment]
@radiohe4d thanks for the note!

You're using Serilog to log to Seq, but `JsonSafeString` is part of the alternative _Seq.Extensions.Logging_ package, which is a different pipeline altogether.

Serilog doesn't have a similar notion, in part because it doesn't assume that the back-end output format is JSON (or even anything textual).

_Seq.Extensions.Logging_ can do it because at this point and the foreseeable future, it's specifically targeting Seq's HTTP ingestion API.

You might consider switching from Serilog across to S.E.L, but unless you need to do this a _lot_, you're better off just logging the JSON string, and using `FromJson` on the Seq side, e.g.:

```sql
FromJson(Answer).A > 40
```

Alternatively, you _could_ implement an enricher in the Serilog pipeline to parse and transform marked JSON values (using a type like `JsonSafeString`) into `LogEventPropertyValue`, though it's likely to be a bit tedious.

Let me know if this helps,
Nick

**Comment by radiohe4d** [comment]
Thanks for getting back so quick Nick!

That's where I've made the mistake, I thought S.E.L was a drop in extension, but now that you mention it, it does make more sense that its a replacement for Serilog.

You've given a few great options for next steps, so ill go have a dig around and see what works best. 

If I come up with anything useful that could help others I'll drop it back here, but happy for this ticket to be closed for now.

Thanks again 👍

**Comment by nblumhardt** [comment]
Thanks @radiohe4d 👍
